sudo: required
language: csharp
dist: xenial
dotnet: 5.0
mono: none
os: linux
solution: LotteryApp.sln
addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell
install:
  - dotnet restore
#  - dotnet tool install -g dotnet-sonarscanner
#  - dotnet tool install --global coverlet.console

branches:
  only:
    - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - xvfb
script:
#  - dotnet-sonarscanner begin /k:"rsmivb_LotteryApp" /o:"rsmivb-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONAR_TOKEN"
  - dotnet build
  - dotnet test Lottery.Models.Test/Lottery.Models.Test.csproj
  - dotnet test Lottery.Service.Tests/Lottery.Service.Tests.csproj
  - dotnet test Lottery.Api.Test/LotteryApi.Test.csproj
#  - dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
#  - coverlet ./Lottery.Models.Test/bin/Debug/netcoreapp2.2/Lottery.Models.Test.dll --target "dotnet" --targetargs "test ./Lottery.Models.Test/Lottery.Models.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover" --format opencover --output ./testResults/lotteryApp.Model.xml
#  - codecov -f .\testResults\lotteryApp.Model.xml -t $env:CODECOV_TOKEN
#  - coverlet ./Lottery.Api.Test/bin/Debug/netcoreapp2.2/LotteryApi.Test.dll --target "dotnet" --targetargs "test ./Lottery.Api.Test/LotteryApi.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover" --format opencover --output ./testResults/lotteryApp.Api.xml
#  - codecov -f .\testResults\lotteryApp.Api.xml -t $env:CODECOV_TOKEN
#  - coverlet ./Lottery.Service.Tests/bin/Debug/netcoreapp2.2/Lottery.Service.Tests.dll --target "dotnet" --targetargs "test ./Lottery.Service.Tests/Lottery.Service.Tests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover" --format opencover --output ./testResults/lotteryApp.Service.xml
#  - codecov -f .\testResults\lotteryApp.Service.xml -t $env:CODECOV_TOKEN
